-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SELK_APP
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SELK_APP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SELK_APP` DEFAULT CHARACTER SET utf8mb4 ;
USE `SELK_APP` ;

-- -----------------------------------------------------
-- Table `SELK_APP`.`USER_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`USER_TYPE` (
  `NAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`NAME`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`USER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TYPE` VARCHAR(50) NOT NULL,
  `EMAIL` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_USER_USER_TYPE1_idx` (`TYPE` ASC) VISIBLE,
  CONSTRAINT `fk_USER_USER_TYPE1`
    FOREIGN KEY (`TYPE`)
    REFERENCES `SELK_APP`.`USER_TYPE` (`NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`CHAT_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`CHAT_TYPE` (
  `TYPE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TYPE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`CHAT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`CHAT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `DESCRIPTION` TEXT NULL,
  `TAGS` VARCHAR(45) NULL,
  `CREATE_TIME` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `CHAT_TYPE_TYPE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_CHAT_CHAT_TYPE1_idx` (`CHAT_TYPE_TYPE` ASC) VISIBLE,
  CONSTRAINT `fk_CHAT_CHAT_TYPE1`
    FOREIGN KEY (`CHAT_TYPE_TYPE`)
    REFERENCES `SELK_APP`.`CHAT_TYPE` (`TYPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`CONTENT_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`CONTENT_TYPE` (
  `TYPE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TYPE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`CONTENT_SERIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`CONTENT_SERIES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`CONTENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`CONTENT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `AUTHOR` INT NOT NULL,
  `TYPE` VARCHAR(45) NOT NULL,
  `CONTENT_SERIES_ID` INT NOT NULL,
  `PUBLISH_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `TITLE` VARCHAR(255) NOT NULL,
  `CONTENT` TEXT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_CONTENT_USER1_idx` (`AUTHOR` ASC) VISIBLE,
  INDEX `fk_CONTENT_CONTENT_TYPE1_idx` (`TYPE` ASC) VISIBLE,
  INDEX `fk_CONTENT_CONTENT_SERIES1_idx` (`CONTENT_SERIES_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CONTENT_USER1`
    FOREIGN KEY (`AUTHOR`)
    REFERENCES `SELK_APP`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONTENT_CONTENT_TYPE1`
    FOREIGN KEY (`TYPE`)
    REFERENCES `SELK_APP`.`CONTENT_TYPE` (`TYPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONTENT_CONTENT_SERIES1`
    FOREIGN KEY (`CONTENT_SERIES_ID`)
    REFERENCES `SELK_APP`.`CONTENT_SERIES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`USER_PERMISSION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`USER_PERMISSION` (
  `NAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`NAME`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`USER_TYPE_PERMISSION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`USER_TYPE_PERMISSION` (
  `USER_TYPE_NAME` VARCHAR(50) NOT NULL,
  `USER_PERMISSION_NAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`USER_TYPE_NAME`, `USER_PERMISSION_NAME`),
  INDEX `fk_USER_TYPE_has_USER_PERMISSION_USER_PERMISSION1_idx` (`USER_PERMISSION_NAME` ASC) VISIBLE,
  INDEX `fk_USER_TYPE_has_USER_PERMISSION_USER_TYPE_idx` (`USER_TYPE_NAME` ASC) VISIBLE,
  CONSTRAINT `fk_USER_TYPE_has_USER_PERMISSION_USER_TYPE`
    FOREIGN KEY (`USER_TYPE_NAME`)
    REFERENCES `SELK_APP`.`USER_TYPE` (`NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_TYPE_has_USER_PERMISSION_USER_PERMISSION1`
    FOREIGN KEY (`USER_PERMISSION_NAME`)
    REFERENCES `SELK_APP`.`USER_PERMISSION` (`NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`COMMUNITY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`COMMUNITY` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `CHAT_ID` INT NOT NULL,
  `ALIVE` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  INDEX `fk_COMMUNITY_CHAT1_idx` (`CHAT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_COMMUNITY_CHAT1`
    FOREIGN KEY (`CHAT_ID`)
    REFERENCES `SELK_APP`.`CHAT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`CALENDAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`CALENDAR` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`EVENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`EVENT` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `CALENDAR_ID` INT NULL,
  `START` DATETIME NULL,
  `END` DATETIME NULL,
  `INFO` TEXT NULL,
  `CONTACT` INT NULL,
  `COMMUNITY` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_EVENT_CALENDAR1_idx` (`CALENDAR_ID` ASC) VISIBLE,
  INDEX `fk_EVENT_USER1_idx` (`CONTACT` ASC) VISIBLE,
  INDEX `fk_EVENT_COMMUNITY1_idx` (`COMMUNITY` ASC) VISIBLE,
  CONSTRAINT `fk_EVENT_CALENDAR1`
    FOREIGN KEY (`CALENDAR_ID`)
    REFERENCES `SELK_APP`.`CALENDAR` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EVENT_USER1`
    FOREIGN KEY (`CONTACT`)
    REFERENCES `SELK_APP`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EVENT_COMMUNITY1`
    FOREIGN KEY (`COMMUNITY`)
    REFERENCES `SELK_APP`.`COMMUNITY` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`AUDIENCE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`AUDIENCE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `EVENT_ID` INT NULL,
  `COMMUNITY_ID` INT NULL,
  `CHAT_ID` INT NULL,
  `CONTENT_SERIES_ID` INT NULL,
  `CALENDAR_ID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_AUDIENCE_EVENT1_idx` (`EVENT_ID` ASC) VISIBLE,
  INDEX `fk_AUDIENCE_COMMUNITY1_idx` (`COMMUNITY_ID` ASC) VISIBLE,
  INDEX `fk_AUDIENCE_CHAT1_idx` (`CHAT_ID` ASC) VISIBLE,
  INDEX `fk_AUDIENCE_CONTENT_SERIES1_idx` (`CONTENT_SERIES_ID` ASC) VISIBLE,
  INDEX `fk_AUDIENCE_CALENDAR1_idx` (`CALENDAR_ID` ASC) VISIBLE,
  CONSTRAINT `fk_AUDIENCE_EVENT1`
    FOREIGN KEY (`EVENT_ID`)
    REFERENCES `SELK_APP`.`EVENT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AUDIENCE_COMMUNITY1`
    FOREIGN KEY (`COMMUNITY_ID`)
    REFERENCES `SELK_APP`.`COMMUNITY` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AUDIENCE_CHAT1`
    FOREIGN KEY (`CHAT_ID`)
    REFERENCES `SELK_APP`.`CHAT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AUDIENCE_CONTENT_SERIES1`
    FOREIGN KEY (`CONTENT_SERIES_ID`)
    REFERENCES `SELK_APP`.`CONTENT_SERIES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AUDIENCE_CALENDAR1`
    FOREIGN KEY (`CALENDAR_ID`)
    REFERENCES `SELK_APP`.`CALENDAR` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`CHAT_ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`CHAT_ROLE` (
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NAME`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`CHAT_USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`CHAT_USER` (
  `USER_ID` INT NOT NULL,
  `CHAT_ID` INT NOT NULL,
  `CHAT_ROLE_NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`USER_ID`, `CHAT_ID`),
  INDEX `fk_USER_has_CHAT_CHAT1_idx` (`CHAT_ID` ASC) VISIBLE,
  INDEX `fk_USER_has_CHAT_USER1_idx` (`USER_ID` ASC) VISIBLE,
  INDEX `fk_CHAT_USER_CHAT_ROLE1_idx` (`CHAT_ROLE_NAME` ASC) VISIBLE,
  CONSTRAINT `fk_USER_has_CHAT_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `SELK_APP`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_has_CHAT_CHAT1`
    FOREIGN KEY (`CHAT_ID`)
    REFERENCES `SELK_APP`.`CHAT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CHAT_USER_CHAT_ROLE1`
    FOREIGN KEY (`CHAT_ROLE_NAME`)
    REFERENCES `SELK_APP`.`CHAT_ROLE` (`NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`CHAT_PERMISSION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`CHAT_PERMISSION` (
  `NAME` INT NOT NULL,
  PRIMARY KEY (`NAME`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`CHAT_ROLE_PERMISSION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`CHAT_ROLE_PERMISSION` (
  `CHAT_PERMISSION_NAME` INT NOT NULL,
  `CHAT_ROLE_NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CHAT_PERMISSION_NAME`, `CHAT_ROLE_NAME`),
  INDEX `fk_CHAT_PERMISSION_has_CHAT_ROLE_CHAT_ROLE1_idx` (`CHAT_ROLE_NAME` ASC) VISIBLE,
  INDEX `fk_CHAT_PERMISSION_has_CHAT_ROLE_CHAT_PERMISSION1_idx` (`CHAT_PERMISSION_NAME` ASC) VISIBLE,
  CONSTRAINT `fk_CHAT_PERMISSION_has_CHAT_ROLE_CHAT_PERMISSION1`
    FOREIGN KEY (`CHAT_PERMISSION_NAME`)
    REFERENCES `SELK_APP`.`CHAT_PERMISSION` (`NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CHAT_PERMISSION_has_CHAT_ROLE_CHAT_ROLE1`
    FOREIGN KEY (`CHAT_ROLE_NAME`)
    REFERENCES `SELK_APP`.`CHAT_ROLE` (`NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`CHAT_MESSAGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`CHAT_MESSAGE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `AUTHOR` INT NOT NULL,
  `RECIEVER` INT NOT NULL,
  `CHAT_ID` INT NOT NULL,
  `MESSAGE` TEXT NULL,
  `SEND_TIME` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  INDEX `fk_CHAT_MESSAGE_USER1_idx` (`AUTHOR` ASC) VISIBLE,
  INDEX `fk_CHAT_MESSAGE_USER2_idx` (`RECIEVER` ASC) VISIBLE,
  INDEX `fk_CHAT_MESSAGE_CHAT1_idx` (`CHAT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CHAT_MESSAGE_USER1`
    FOREIGN KEY (`AUTHOR`)
    REFERENCES `SELK_APP`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CHAT_MESSAGE_USER2`
    FOREIGN KEY (`RECIEVER`)
    REFERENCES `SELK_APP`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CHAT_MESSAGE_CHAT1`
    FOREIGN KEY (`CHAT_ID`)
    REFERENCES `SELK_APP`.`CHAT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`COMMUNITY_MEMBER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`COMMUNITY_MEMBER` (
  `COMMUNITY_ID` INT NOT NULL,
  `USER_ID` INT NOT NULL,
  PRIMARY KEY (`COMMUNITY_ID`, `USER_ID`),
  INDEX `fk_COMMUNITY_has_USER_USER1_idx` (`USER_ID` ASC) VISIBLE,
  INDEX `fk_COMMUNITY_has_USER_COMMUNITY1_idx` (`COMMUNITY_ID` ASC) VISIBLE,
  CONSTRAINT `fk_COMMUNITY_has_USER_COMMUNITY1`
    FOREIGN KEY (`COMMUNITY_ID`)
    REFERENCES `SELK_APP`.`COMMUNITY` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMMUNITY_has_USER_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `SELK_APP`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`USER_AUDIENCE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`USER_AUDIENCE` (
  `AUDIENCE_ID` INT NOT NULL,
  `USER_ID` INT NOT NULL,
  PRIMARY KEY (`AUDIENCE_ID`, `USER_ID`),
  INDEX `fk_AUDIENCE_has_USER_USER1_idx` (`USER_ID` ASC) VISIBLE,
  INDEX `fk_AUDIENCE_has_USER_AUDIENCE1_idx` (`AUDIENCE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_AUDIENCE_has_USER_AUDIENCE1`
    FOREIGN KEY (`AUDIENCE_ID`)
    REFERENCES `SELK_APP`.`AUDIENCE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AUDIENCE_has_USER_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `SELK_APP`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`EVENT_USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`EVENT_USER` (
  `EVENT_ID` INT NOT NULL,
  `USER_ID` INT NOT NULL,
  PRIMARY KEY (`EVENT_ID`, `USER_ID`),
  INDEX `fk_EVENT_has_USER_USER1_idx` (`USER_ID` ASC) VISIBLE,
  INDEX `fk_EVENT_has_USER_EVENT1_idx` (`EVENT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_EVENT_has_USER_EVENT1`
    FOREIGN KEY (`EVENT_ID`)
    REFERENCES `SELK_APP`.`EVENT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EVENT_has_USER_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `SELK_APP`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`CALENDAR_SUBSCRIPTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`CALENDAR_SUBSCRIPTION` (
  `CALENDAR_ID` INT NOT NULL,
  `USER_ID` INT NOT NULL,
  PRIMARY KEY (`CALENDAR_ID`, `USER_ID`),
  INDEX `fk_CALENDAR_has_USER_USER1_idx` (`USER_ID` ASC) VISIBLE,
  INDEX `fk_CALENDAR_has_USER_CALENDAR1_idx` (`CALENDAR_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CALENDAR_has_USER_CALENDAR1`
    FOREIGN KEY (`CALENDAR_ID`)
    REFERENCES `SELK_APP`.`CALENDAR` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CALENDAR_has_USER_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `SELK_APP`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`CHAT_POLICY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`CHAT_POLICY` (
  `POLICY` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`POLICY`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`CHAT_TYPE_POLICY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`CHAT_TYPE_POLICY` (
  `CHAT_TYPE_TYPE` VARCHAR(45) NOT NULL,
  `CHAT_POLICY_POLICY` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CHAT_TYPE_TYPE`, `CHAT_POLICY_POLICY`),
  INDEX `fk_CHAT_TYPE_has_CHAT_POLICY_CHAT_POLICY1_idx` (`CHAT_POLICY_POLICY` ASC) VISIBLE,
  INDEX `fk_CHAT_TYPE_has_CHAT_POLICY_CHAT_TYPE1_idx` (`CHAT_TYPE_TYPE` ASC) VISIBLE,
  CONSTRAINT `fk_CHAT_TYPE_has_CHAT_POLICY_CHAT_TYPE1`
    FOREIGN KEY (`CHAT_TYPE_TYPE`)
    REFERENCES `SELK_APP`.`CHAT_TYPE` (`TYPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CHAT_TYPE_has_CHAT_POLICY_CHAT_POLICY1`
    FOREIGN KEY (`CHAT_POLICY_POLICY`)
    REFERENCES `SELK_APP`.`CHAT_POLICY` (`POLICY`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`SETTING_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`SETTING_TYPE` (
  `TYPE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TYPE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`SETTING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`SETTING` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(45) NULL,
  `POSITION` INT NULL,
  `GROUP` VARCHAR(255) NULL,
  `SETTING_TYPE_TYPE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_SETTING_SETTING_TYPE1_idx` (`SETTING_TYPE_TYPE` ASC) VISIBLE,
  CONSTRAINT `fk_SETTING_SETTING_TYPE1`
    FOREIGN KEY (`SETTING_TYPE_TYPE`)
    REFERENCES `SELK_APP`.`SETTING_TYPE` (`TYPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`SETTING_OPTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`SETTING_OPTION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `SETTING_ID` INT NOT NULL,
  `VALUE` VARCHAR(45) NULL,
  INDEX `fk_SETTING_OPTION_SETTING1_idx` (`SETTING_ID` ASC) VISIBLE,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_SETTING_OPTION_SETTING1`
    FOREIGN KEY (`SETTING_ID`)
    REFERENCES `SELK_APP`.`SETTING` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`USER_SETTINGS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`USER_SETTINGS` (
  `USER_ID` INT NOT NULL,
  `SETTING_ID` INT NOT NULL,
  `VALUE` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`USER_ID`, `SETTING_ID`),
  INDEX `fk_USER_has_SETTING_SETTING1_idx` (`SETTING_ID` ASC) VISIBLE,
  INDEX `fk_USER_has_SETTING_USER1_idx` (`USER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_USER_has_SETTING_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `SELK_APP`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_has_SETTING_SETTING1`
    FOREIGN KEY (`SETTING_ID`)
    REFERENCES `SELK_APP`.`SETTING` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`DEVICE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`DEVICE` (
  `ID` VARCHAR(255) NOT NULL,
  `USER_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_DEVICE_USER1_idx` (`USER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_DEVICE_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `SELK_APP`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SELK_APP`.`CONTENT_AUDIENCE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SELK_APP`.`CONTENT_AUDIENCE` (
  `CONTENT_ID` INT NOT NULL,
  `AUDIENCE_ID` INT NOT NULL,
  PRIMARY KEY (`CONTENT_ID`, `AUDIENCE_ID`),
  INDEX `fk_CONTENT_has_AUDIENCE_AUDIENCE1_idx` (`AUDIENCE_ID` ASC) VISIBLE,
  INDEX `fk_CONTENT_has_AUDIENCE_CONTENT1_idx` (`CONTENT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CONTENT_has_AUDIENCE_CONTENT1`
    FOREIGN KEY (`CONTENT_ID`)
    REFERENCES `SELK_APP`.`CONTENT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONTENT_has_AUDIENCE_AUDIENCE1`
    FOREIGN KEY (`AUDIENCE_ID`)
    REFERENCES `SELK_APP`.`AUDIENCE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
