name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: self-hosted

    steps:  
    - uses: actions/checkout@v3
    
    - name: create Tag Name
      run: export TAGNAME=$(date +%s)
      
    - name: display Tag Name
      run: echo $TAGNAME
    
    - name: Build the Docker image
      run: docker build . --file mysql/Dockerfile --tag mysql:$(echo $TAGNAME)
    
    - name: Login to DockerHub
      run: docker login --username ${{secrets.DOCKER_USERNAME}} -password ${{secrets.DOCKER_PASSWORD}}
      
    - name: Push Image
      run: docker push ${{secrets.DOCKER_USERNAME}}/mysql:$(echo $TAGNAME)


