name: MySQL DockerHub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    
    - name: checkout Repo
      uses: actions/checkout@v3
      
    - name: create MYSQL Root Password Secret
      run: echo "${{ secrets.MYSQL_ROOT_PASSWORD }}" > MYSQL_ROOT_PASSWORD.txt
      
    - name: create MYSQL User Secret
      run: echo "${{ secrets.MYSQL_USER }}" > MYSQL_USER.txt

    - name: create MYSQL User Password Secret
      run: echo "${{ secrets.MYSQL_PASSWORD }}" > MYSQL_PASSWORD.txt

    - name: create MYSQL DB Secret
      run: echo "${{ secrets.MYSQL_DB }}" > MYSQL_DB.txt
        
    - name: Build the Docker image
      run: docker build
            --file mysql/Dockerfile 
            --tag ${{ secrets.DOCKER_USERNAME }}/mysql:latest 
            --secret id=MYSQL_ROOT_PASSWORD,src=MYSQL_ROOT_PASSWORD.txt
            --secret id=MYSQL_USER,src=MYSQL_USER.txt
            --secret id=MYSQL_PASSWORD,src=MYSQL_PASSWORD.txt
            --secret id=MYSQL_DB,src=MYSQL_DB.txt .
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Push Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/mysql:latest


